theme = "doom_acario_dark"

[editor]
cursorline = true
color-modes = true
bufferline = "always"

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "position-percentage","file-encoding"]
separator = "│"

[editor.indent-guides]
render = true

